# Generated by Django 4.0.5 on 2022-06-03 20:47

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=65)),
                ('email', models.EmailField(max_length=254, verbose_name='Mail del Profesor')),
                ('fecha_contratacion', models.DateField(default=time.time)),
            ],
        ),
    ]
