# Generated by Django 4.0.5 on 2022-06-05 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_nombre_asignatura_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignatura',
            old_name='apellido',
            new_name='nombre',
        ),
    ]
