# Generated by Django 4.0.5 on 2022-06-06 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_rename_apellido_asignatura_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='fecha_contratacion',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 6)),
        ),
    ]
